### ISSUE TITLE
Does not work with Realm-0.86

### ISSUE THREAD

**Issue by zaki50** [uPhyca/stetho-realm#9]
We need to update stetho-realm

**Comment by jemshit** [comment]
Error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/internal/ColumnType;
at com.uphyca.stetho_realm.Database$2.
<clinit>
(Database.java:163)
at com.uphyca.stetho_realm.Database.flattenRows(Database.java:163)
at com.uphyca.stetho_realm.Database.access$300(Database.java:37)
at com.uphyca.stetho_realm.Database$1.handleSelect(Database.java:121)
at com.uphyca.stetho_realm.Database$1.handleSelect(Database.java:101)
at com.uphyca.stetho_realm.RealmPeerManager.executeSQL(RealmPeerManager.java:123)
at com.uphyca.stetho_realm.Database.executeSQL(Database.java:100)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:46)
at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:154)
at com.facebook.stetho.websocket.WebSocketHandler.handleSecured(WebSocketHandler.java:106)
at com.facebook.stetho.server.SecureHttpRequestHandler.handle(SecureHttpRequestHandler.java:52)
at org.apache.http.protocol.HttpService.doService(HttpService.java:243)
at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:187)
at com.facebook.stetho.server.LocalSocketHttpServer$WorkerThread.run(LocalSocketHttpServer.java:233)
...
Suppressed: java.lang.ClassNotFoundException: io.realm.internal.ColumnType
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 25 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by emanuelet** [comment]
+1

**Comment by zaki50** [comment]
Thank you for reportig.

I must follow the changes of Realm 0.86.

I have no time for updating Stetho-Realm this weeked.

I'll update this in early next week.

Thanks

**Comment by bsphere** [comment]
+1

**Comment by r-cohen** [comment]
++

**Comment by euitam** [comment]
Hi there, any news on the update?
Thanks a lot!

**Comment by zaki50** [comment]
Sorry for delay.
I will update today

**Comment by rgrinberg** [comment]
+1. I'd really like to play around with this.

**Comment by zaki50** [comment]
released 0.8.0 which supports 0.86.0 or later.

So sorry for keeping you waiting.

**Comment by zaki50** [comment]
I'll close this issue.

If anyone will find the problem, feel free to reopen this or to create new issue.

**Comment by vickychijwani** [comment]
Thanks, @zaki50!
